#!/bin/csh -f
#
# Mach Operating System
# Copyright (c) 1991,1990,1989 Carnegie Mellon University
# All Rights Reserved.
# 
# Permission to use, copy, modify and distribute this software and its
# documentation is hereby granted, provided that both the copyright
# notice and this permission notice appear in all copies of the
# software, derivative works or modified versions, and any portions
# thereof, and that both notices appear in supporting documentation.
# 
# CARNEGIE MELLON ALLOWS FREE USE OF THIS SOFTWARE IN ITS 
# CONDITION.  CARNEGIE MELLON DISCLAIMS ANY LIABILITY OF ANY KIND FOR
# ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
# 
# Carnegie Mellon requests users of this software to return to
# 
#  Software Distribution Coordinator  or  Software.Distribution@CS.CMU.EDU
#  School of Computer Science
#  Carnegie Mellon University
#  Pittsburgh PA 15213-3890
# 
# any improvements or extensions that they make and grant Carnegie the
# rights to redistribute these changes.
#
#
# HISTORY
# $Log:	mk,v $
# Revision 2.2  91/02/05  17:53:13  mrt
# 	Changed to new Mach copyright
# 	[91/02/01  17:51:51  mrt]
# 
# Revision 2.1  89/08/03  18:12:38  rwd
# Created.
# 
# Revision 2.2  89/02/25  19:22:00  gm0w
# 	Changes for cleanup.
# 
# 08-Jan-87  Robert Beck (beck) at Sequent Computer Systems, Inc.
#	Shell to invoke Makefile for parallel make and -DCMU.
#

make "P=&" CFLAGS="-O -DCMU" -P10
