# 
# Mach Operating System
# Copyright (c) 1987 Carnegie-Mellon University
# All rights reserved.  The CMU software License Agreement specifies
# the terms and conditions for use and redistribution.
#
######################################################################
# HISTORY
# $Log:	Makefile.config,v $
# Revision 2.1  89/08/04  15:25:49  rwd
# Created.
# 
# Revision 2.3  88/07/20  16:20:04  rpd
# Execute config as ../bin/config.
# 
# 09-Nov-87  Mike Accetta (mja) at Carnegie-Mellon University
#	Created (extracted parts from src/doconf.csh).
#	[ V5.1(XF21) ]
#
######################################################################
#

${SYS}:	${MASTER}
	@echo +${SYS} \
	| \
	cat ${MASTER} - ${MASTER} \
	| \
	sed -n \
	-e "/^+/{" \
	   -e "s;[-+];#&;gp" \
	      -e 't loop' \
	   -e ': loop' \
	       -e 'n' \
	   -e '/^#/b loop' \
	   -e '/^$$/b loop' \
	   -e 's;^\([^#]*\).*#[ 	]*<\(.*\)>[ 	]*$$;\2#\1;' \
	      -e 't not' \
	   -e 's;\([^#]*\).*;#\1;' \
	      -e 't not' \
	   -e ': not' \
	   -e 's;[ 	]*$$;;' \
	   -e 's;^!\(.*\);\1#!;' \
	   -e 'p' \
	      -e 't loop' \
	       -e 'b loop' \
	-e '}' \
	-e "/^[^#]/d" \
	-e 's;	; ;g' \
	-e "s;^# *\([^ ]*\)[ ]*=[ ]*\[\(.*\)\].*;\1#\2;p" \
	| \
	awk '-F#' '\
 part == 0 && $$1 != "" {\
	m[$$1]=m[$$1] " " $$2;\
	next;\
 }\
 part == 0 && $$1 == "" {\
	for (i=NF;i>1;i--){\
		s=substr($$i,2);\
		c[++na]=substr($$i,1,1);\
		a[na]=s;\
	}\
	while (na > 0){\
		s=a[na];\
		d=c[na--];\
		if (m[s] == "") {\
			f[s]=d;\
		} else {\
			nx=split(m[s],x," ");\
			for (j=nx;j>0;j--) {\
				z=x[j];\
				a[++na]=z;\
				c[na]=d;\
			}\
		}\
	}\
	part=1;\
	next;\
	}\
	part != 0 {\
	if ($$1 != "") {\
		n=split($$1,x,",");\
		ok=0;\
		for (i=1;i<=n;i++) {\
			if (f[x[i]] == "+") {\
				ok=1;\
			}\
		}\
		if (NF > 2 && ok == 0 || NF <= 2 && ok != 0) {\
			print $$2; \
		}\
	} else { \
		print $$2; \
	}\
	}' >${SYS}.tmp
	@-if [ -s ${SYS}.tmp ]; then \
	    if [ -f ${SYS} ]; then \
		diff ${SYS} ${SYS}.tmp; \
		cp -p ${SYS} ${SYS}.old; \
	    fi; \
	    cp -p ${SYS}.tmp ${SYS}; \
	fi; \
	rm -f ${SYS}.tmp;

${SYS}.config:	${SYS} ../conf/files ../conf/files.${cpu} \
	../conf/Makefile.template ../conf/Makefile.${cpu}
	../bin/config ${SYS}
